### ISSUE TITLE
Not able to run binnacle on apple m1

### ISSUE THREAD

**Issue by cogito-abhijeet** [Traackr/binnacle#11]
Mac big sur version 11.4 shows segmentation fault issue

```
binnacle --version
zsh: segmentation fault  binnacle --version
```

**Comment by jmmk** [comment]
@cogito-abhijeet The existing `binnacle-darwin_amd64.tar.gz` artifact is compiled for x86_64 CPU architecture and not the ARM64 architecture of the M1 CPU. I don't have an M1 device, so I wouldn't be able to test this, but I imagine the steps to produce a working release would be something like:

- Upgrade to go 1.16, which includes support for cross compiling to the with `GOOS=darwin GOARCH=arm64` flags
- tweak `scripts/build.sh` to include `darwin_arm64` as a target
- run the build

**Comment by cogito-abhijeet** [comment]
Thanks you. I was able to create binary locally with above instructions.

**Comment by jmmk** [comment]
Starting with version `0.7.0`, there is now a `darwin_arm64` artifact being produced
